# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sail-cameras',
                'doc_host': 'https://SAIL-Labs.github.io',
                'git_url': 'https://github.com/SAIL-Labs/sail-cameras',
                'lib_path': 'sail_cameras'},
  'syms': {'sail_cameras.core': {'sail_cameras.core.foo': ('core.html#foo', 'sail_cameras/core.py')}}}
