project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    keep-md: true
  commonmark: default

website:
  twitter-card: false
  open-graph: true
  repo-actions: [source, issue]
  navbar:
    title: "A helpful camera interface."
    background: primary
    search: true
  search: 
    location: sidebar
    type: textbox
  sidebar:
    style: floating
    search: true

metadata-files: [nbdev.yml, sidebar.yml]